CORE = superrt

VSRC = address.v clk_test.v dac.v dcm.v srt_engine.v srt_mul.v superrt.v main.v mcu_cmd.v msu.v sd_dma.v spi.v
VHSRC =

COMMON_IP = dac_buf msu_databuf snescmd_buf

XIL_IP =
XIL_IPCORE_DIR = ip/mk2

INT_IP = pll

include ../settings.mk
include ../common.mk
